#!/usr/bin/env python3
"""Generate `av1/cdf.rs` from the AV1 specification's default CDF tables.

The AV1 default CDFs are several thousand constants. Hand-transcribing them is a
bug source with no upside, so — like the REFERENCE manifests — they are
generated and CI re-runs this and `git diff --exit-code`s the result.

Input is a vendored extract of the ``~~~~ c`` blocks that define the
``Default_*_Cdf`` tables in section 10 (Additional tables) of the AV1 spec,
kept at ``scripts/data/av1-default-cdf-tables.txt`` so the generation is
reproducible without network access and the source is traceable. Each innermost
array is already in the exact shape ``SymbolDecoder`` consumes: ``N`` cumulative
frequencies ending in ``1 << 15``, then a trailing ``0`` adaptation counter.

Usage::

    python3 scripts/generate-av1-cdf-tables.py

Writes ``crates/otf-pixels-codec-avif/src/av1/cdf.rs``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "scripts" / "data" / "av1-default-cdf-tables.txt"
OUT = ROOT / "crates" / "otf-pixels-codec-avif" / "src" / "av1" / "cdf.rs"


def strip_comments(text: str) -> str:
    """Remove ``//`` line comments so a provenance header can sit in the input."""
    return "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("//"))


def parse_initializer(tokens: list[str], pos: int):
    """Parse a C brace initializer into nested Python lists of ints."""
    assert tokens[pos] == "{", f"expected '{{' at {pos}, got {tokens[pos]!r}"
    pos += 1
    items: list = []
    while True:
        tok = tokens[pos]
        if tok == "}":
            return items, pos + 1
        if tok == "{":
            sub, pos = parse_initializer(tokens, pos)
            items.append(sub)
        elif tok == ",":
            pos += 1
        else:
            items.append(int(tok))
            pos += 1


def tokenize(body: str) -> list[str]:
    return re.findall(r"\{|\}|,|-?\d+", body)


def shape_of(data) -> list[int]:
    dims: list[int] = []
    node = data
    while isinstance(node, list):
        dims.append(len(node))
        node = node[0] if node else None
    return dims


def rust_type(dims: list[int]) -> str:
    t = "u16"
    for d in reversed(dims):
        t = f"[{t}; {d}]"
    return t


def rust_value(data) -> str:
    if isinstance(data, int):
        return str(data)
    return "[" + ", ".join(rust_value(x) for x in data) + "]"


def const_name(table: str) -> str:
    # Default_Intra_Frame_Y_Mode_Cdf -> DEFAULT_INTRA_FRAME_Y_MODE_CDF
    return table.upper()


def main() -> int:
    text = strip_comments(SPEC.read_text())

    # Each definition: Default_<Name>_Cdf[ dim ][ dim ]... = { ... }
    pattern = re.compile(
        r"(Default_\w+_Cdf)\s*((?:\[[^\]]*\]\s*)+)=\s*(\{.*?\})\s*(?=Default_\w+_Cdf\s*\[|$)",
        re.DOTALL,
    )
    tables = []
    for m in pattern.finditer(text):
        name = m.group(1)
        body = m.group(3)
        tokens = tokenize(body)
        data, end = parse_initializer(tokens, 0)
        if end != len(tokens):
            print(f"warning: trailing tokens after {name}", file=sys.stderr)
        tables.append((name, data))

    if not tables:
        print("error: no CDF tables parsed", file=sys.stderr)
        return 1

    lines = [
        "//! Default CDF tables for the AV1 symbol decoder.",
        "//!",
        "//! GENERATED by `scripts/generate-av1-cdf-tables.py` from the AV1",
        "//! specification's section 10 default tables. Do not edit by hand; edit the",
        "//! generator or its vendored input and re-run it. CI re-runs it and",
        "//! `git diff --exit-code`s this file, exactly as it does the REFERENCE",
        "//! manifests, so a hand edit or a stale table is caught.",
        "//!",
        "//! Each innermost array is a CDF ready for `SymbolDecoder::read_symbol`:",
        "//! the cumulative frequencies ending in `1 << 15`, then a `0` counter.",
        "",
        "#![cfg_attr(rustfmt, rustfmt::skip)]",
        "",
    ]
    for name, data in sorted(tables):
        dims = shape_of(data)
        lines.append(f"/// `{name}` ({'x'.join(map(str, dims))}).")
        lines.append(f"pub static {const_name(name)}: {rust_type(dims)} = {rust_value(data)};")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} with {len(tables)} tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
